package com.zkp.gank.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zkp.gank.greendao.entities.CollectionArticles;

import com.zkp.gank.greendao.CollectionArticlesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionArticlesDaoConfig;

    private final CollectionArticlesDao collectionArticlesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionArticlesDaoConfig = daoConfigMap.get(CollectionArticlesDao.class).clone();
        collectionArticlesDaoConfig.initIdentityScope(type);

        collectionArticlesDao = new CollectionArticlesDao(collectionArticlesDaoConfig, this);

        registerDao(CollectionArticles.class, collectionArticlesDao);
    }
    
    public void clear() {
        collectionArticlesDaoConfig.clearIdentityScope();
    }

    public CollectionArticlesDao getCollectionArticlesDao() {
        return collectionArticlesDao;
    }

}
