package com.zkp.gank.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zkp.gank.db.entity.RefreshTime;
import com.zkp.gank.db.entity.SearchHistory;

import com.zkp.gank.db.greendao.RefreshTimeDao;
import com.zkp.gank.db.greendao.SearchHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig refreshTimeDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;

    private final RefreshTimeDao refreshTimeDao;
    private final SearchHistoryDao searchHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        refreshTimeDaoConfig = daoConfigMap.get(RefreshTimeDao.class).clone();
        refreshTimeDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        refreshTimeDao = new RefreshTimeDao(refreshTimeDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);

        registerDao(RefreshTime.class, refreshTimeDao);
        registerDao(SearchHistory.class, searchHistoryDao);
    }
    
    public void clear() {
        refreshTimeDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
    }

    public RefreshTimeDao getRefreshTimeDao() {
        return refreshTimeDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

}
