package com.zkp.gank.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zkp.gank.db.entity.SearchHistory;
import com.zkp.gank.db.entity.Address;

import com.zkp.gank.db.greendao.SearchHistoryDao;
import com.zkp.gank.db.greendao.AddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig addressDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final AddressDao addressDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);

        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(Address.class, addressDao);
    }
    
    public void clear() {
        searchHistoryDaoConfig.clearIdentityScope();
        addressDaoConfig.clearIdentityScope();
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

}
