package com.zkp.gank.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zkp.gank.db.entity.RefreshTime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REFRESH_TIME".
*/
public class RefreshTimeDao extends AbstractDao<RefreshTime, Long> {

    public static final String TABLENAME = "REFRESH_TIME";

    /**
     * Properties of entity RefreshTime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property CurrentTime = new Property(2, long.class, "currentTime", false, "CURRENT_TIME");
        public final static Property LastRefreshTime = new Property(3, long.class, "lastRefreshTime", false, "LAST_REFRESH_TIME");
    }


    public RefreshTimeDao(DaoConfig config) {
        super(config);
    }
    
    public RefreshTimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REFRESH_TIME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"CURRENT_TIME\" INTEGER NOT NULL ," + // 2: currentTime
                "\"LAST_REFRESH_TIME\" INTEGER NOT NULL );"); // 3: lastRefreshTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REFRESH_TIME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RefreshTime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getCurrentTime());
        stmt.bindLong(4, entity.getLastRefreshTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RefreshTime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindLong(3, entity.getCurrentTime());
        stmt.bindLong(4, entity.getLastRefreshTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RefreshTime readEntity(Cursor cursor, int offset) {
        RefreshTime entity = new RefreshTime( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.getLong(offset + 2), // currentTime
            cursor.getLong(offset + 3) // lastRefreshTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RefreshTime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCurrentTime(cursor.getLong(offset + 2));
        entity.setLastRefreshTime(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RefreshTime entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RefreshTime entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RefreshTime entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
